# Generated by Django 3.1.7 on 2021-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FcCollectionType',
            fields=[
                ('fcCollectionType_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('fcCollectionType_name', models.CharField(max_length=50)),
                ('fcCollectionType_desc', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
