# Generated by Django 3.1.7 on 2021-05-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcCollections', '0002_fccollection_fccollection_type_id'),
        ('flashCard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='fcCollection_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fcCollections.fccollection'),
            preserve_default=False,
        ),
    ]
