# Generated by Django 3.1.7 on 2021-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FcCollection',
            fields=[
                ('fcCollection_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fcCollection_title', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
