# Generated by Django 3.1.7 on 2021-05-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcCollectionType', '0001_initial'),
        ('fcCollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fccollection',
            name='fcCollection_type_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fcCollectionType.fccollectiontype'),
            preserve_default=False,
        ),
    ]
