# Generated by Django 3.1.7 on 2021-05-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcCollections', '0002_fccollection_fccollection_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fccollection',
            old_name='fcCollection_type_id',
            new_name='fcCollectionType_id',
        ),
    ]
