# Generated by Django 3.1.7 on 2021-05-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcCollections', '0003_auto_20210503_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='fccollection',
            name='fcCollection_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
